### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'Graph'

### ISSUE THREAD

**Issue by BernieLBY** [kiddyboots216/FedRL#2]
Dear author, when i tested the code, i got an error, could you please help me?
2019-06-11 17:27:11,676	ERROR trial_runner.py:487 -- Error processing event.
Traceback (most recent call last):
  File "/home/ethan/anaconda3/envs/gymlab/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 436, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/ethan/anaconda3/envs/gymlab/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 323, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/ethan/anaconda3/envs/gymlab/lib/python3.6/site-packages/ray/worker.py", line 2189, in get
    raise value
ray.exceptions.RayTaskError: ray_worker (pid=29306, host=ethan)
  File "/home/ethan/anaconda3/envs/gymlab/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 311, in __init__
    Trainable.__init__(self, config, logger_creator)
  File "/home/ethan/anaconda3/envs/gymlab/lib/python3.6/site-packages/ray/tune/trainable.py", line 88, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/home/ethan/anaconda3/envs/gymlab/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 424, in _setup
    self._init(self.config, self.env_creator)
  File "/home/ethan/anaconda3/envs/gymlab/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 63, in _init
    env_creator, policy)
  File "/home/ethan/anaconda3/envs/gymlab/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 622, in make_local_evaluator
    extra_config or {}))
  File "/home/ethan/anaconda3/envs/gymlab/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 847, in _make_evaluator
    _fake_sampler=config.get("_fake_sampler", False))
  File "/home/ethan/anaconda3/envs/gymlab/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 312, in __init__
    with tf.Graph().as_default():
AttributeError: 'NoneType' object has no attribute 'Graph'

2019-06-11 17:27:11,677	INFO ray_trial_executor.py:187 -- Destroying actor for trial PPO_multienv_FedRL_0. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/8 CPUs, 0/1 GPUs
Memory usage on this node: 5.4/16.8 GB
Result logdir: /home/ethan/ray_results/HalfCheetah-v2-PPO-5
Number of trials: 1 ({'ERROR': 1})
ERROR trials:
 - PPO_multienv_FedRL_0:	ERROR, 1 failures: /home/ethan/ray_results/HalfCheetah-v2-PPO-5/PPO_multienv_FedRL_0_2019-06-11_17-27-1080na_7ja/error_2019-06-11_17-27-11.txt

Traceback (most recent call last):
  File "FedRL.py", line 213, in <module>
    fedrl(args)
  File "FedRL.py", line 193, in fedrl
    checkpoint_at_end=True
  File "/home/ethan/anaconda3/envs/gymlab/lib/python3.6/site-packages/ray/tune/tune.py", line 272, in run
    raise TuneError("Trials did not complete", errored_trials)
ray.tune.error.TuneError: ('Trials did not complete', [PPO_multienv_FedRL_0])

**Comment by kiddyboots216** [comment]
Please see updated README
